### ISSUE TITLE
go.mod: unknown revision 000000000000

### ISSUE THREAD

**Issue by cryptix** [9fans/go#31]
when I try to `go get -u ./...` a project that uses this I just get this error:
```
...
Fetching https://9fans.net/go?go-get=1
Parsing meta tags from https://9fans.net/go?go-get=1 (status code 200)
get "9fans.net/go": found meta tag get.metaImport{Prefix:"9fans.net/go", VCS:"git", RepoRoot:"https://github.com/9fans/go"} at https://9fans.net/go?go-get=1
go: finding 9fans.net/go v0.0.0-00010101000000-000000000000
go: 9fans.net/go@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
go: error loading module requirements
```

I see that there is no tagged release yet but `@master` should still work, no?

**Comment by cryptix** [comment]
When I try `@master` however I get this:

```
go get -v 9fans.net/go@master
Fetching https://9fans.net/go?go-get=1
Parsing meta tags from https://9fans.net/go?go-get=1 (status code 200)
get "9fans.net/go": found meta tag get.metaImport{Prefix:"9fans.net/go", VCS:"git", RepoRoot:"https://github.com/9fans/go"} at https://9fans.net/go?go-get=1
go: finding 9fans.net/go master
go: finding 9fans.net/go latest
Fetching https://9fans.net?go-get=1

https fetch failed: Get http://plan9.bell-labs.com/plan9/: dial tcp: lookup plan9.bell-labs.com: device or resource busy
```

I don't know why it falls back to that domain, I guess it's part of the HTML meta tag?

**Comment by rsc** [comment]
https://9fans.net redirects to http://plan9.bell-labs.com/plan9, but the go command should not have gotten down that far. https://9fans.net/go should have worked and clearly didn't. Not sure why.

**Comment by cryptix** [comment]
I was confused as well since it finds the RepoRoot at github and I trust that if that was the broken part, other people would have noticed by now.. It's a persistent issue, though.

Will report more details once I untangled them.

**Comment by rsc** [comment]
Seems to be working now.
