### ISSUE TITLE
license is not recognized by pkg.go.dev

### ISSUE THREAD

**Issue by rogpeppe** [9fans/go#36]
The Go docs aren't visible on pkg.go.dev ("README not displayed due to license restrictions").

     https://pkg.go.dev/9fans.net/go/draw?tab=overview

It would be nice to fix this if possible.

**Comment by rsc** [comment]
I was working on it in early March (on the license detector side) but got interrupted by covid. Trying to get back to it.

**Comment by rsc** [comment]
<img width="506" alt="Screen Shot 2021-04-16 at 9 04 04 PM" src="https://user-images.githubusercontent.com/104030/115097309-48c65400-9ef7-11eb-899b-865332f9cd8d.png">
