### ISSUE TITLE
how-to <build> in readme

### ISSUE THREAD

**Issue by mushkevych** [9fans/go#41]
Newbie to both Plan9 and Golang here. Please excuse using **Issues** as a communication channel - will happily use another if provided.
Trying to build the packages, but **makefile** returns:
```
:~/workspace/9fans/go.git/acme$ make
Makefile:1: /usr/local/go/src/Make.inc: No such file or directory
Makefile:7: /usr/local/go/src/Make.pkg: No such file or directory
make: *** No rule to make target '/usr/local/go/src/Make.pkg'.  Stop.
```
my GOROOT is pointing to the Golang deployment as below:
```
~/workspace/9fans/go.git/acme$ $GOROOT/bin/go version
go version go1.15.2 linux/amd64
```

It would be great if README contained a section on build steps.

**Comment by fhs** [comment]
If you're trying to build and run acme, this is the wrong repo. You want to install [plan9port](https://9fans.github.io/plan9port/), which comes with acme and many other Plan 9 tools that run on unix.

**Comment by mushkevych** [comment]
@fhs  thank you for reply. I am wondering whether it would be a good addition to the README file to mention how each package is supposed to be build and used. For instance, the `Makefile` is referencing `$GOROOT/src/Make.inc` and `$GOROOT/src/Make.pkg`, while none of those files are present in the [Go codebase](https://github.com/golang/go/tree/master/src)
Should we expect that `planplan9port` build mechanism will create those files?

**Comment by fhs** [comment]
@mushkevych The makefiles are left over from long ago when Go used to use them. They should be removed (PR #24).

I don't think there is a need to add anything to README. It should already be clear to any Go programmer how to use this package. I suggest studying how to build a Go programs first. See https://golang.org/doc/code.html#ImportingRemote

**Comment by mushkevych** [comment]
@fhs #24 clarified it all. Thank you. Closing this issue.
